### ISSUE TITLE
increaseRank() should be independent and not take any parameter

### ISSUE THREAD

**Issue by ynotrusso** [Jryke/k-02-js#2]
https://github.com/Jryke/k-02-js/blob/f006dd83e1cbc4a19fa011169b7fc8e42b279ea7/classes.js#L67

**Comment by Jryke** [comment]
resolved by moving logic into increaseRank() function (rather than logic in if statement and passing value into the function).  IncreaseRank() now working without requiring a parameter.

Also, if statement changed to ternary operator because it is now only one line of code.
